### ISSUE TITLE
[SpongeForge] - Nether generation lags

### ISSUE THREAD

**Issue by SSKirillSS** [paulevsGitch/BetterNether#13]
Hey. For several months now I've been watching the server just unrealistically lag during the generation of Nether, TPS drops to almost 3. In the server logs almost no information. Any thoughts on this?
P.S. - server hardware is quite expensive, and it's definitely not the fault.

SpongeForge - spongeforge-1.12.2-2768-7.1.6-RC3596
Forge - forge-1.12.2-14.23.5.2807-universal
BetterNether - betternether-0.1.8.2-1.12.2

**Comment by paulevsGitch** [comment]
Maybe it is due to a bug with nether wart biome generation. It will be fixed in the future, you can disable this biome in the config.

**Comment by SSKirillSS** [comment]
Did not help.
![image](https://user-images.githubusercontent.com/38190325/54072336-8d984f00-428a-11e9-8323-b5d079634717.png)
When loaded this area TPS lowered to 7.

Configurations that I changed:
    B:biome_wart_forest_edge=false
    B:biome_wart_forest=false
    S:WartForestDensity=0.0

**Comment by paulevsGitch** [comment]
Does this issue appear only on Spongeforge? What other mods are installed and is it actually issue of my mod?

**Comment by SSKirillSS** [comment]
Sorry, I can't test, but I found something funny:
```
Thread: Server thread, state: RUNNABLE
    at paulevs.betternether.noise.WorleyNoiseIDDistorted3D.GetValue(WorleyNoiseIDDistorted3D.java:28)
    at paulevs.betternether.world.BNWorldGenerator.getBiome(BNWorldGenerator.java:256)
    at paulevs.betternether.world.BNWorldGenerator.isEdge(BNWorldGenerator.java:244)
    at paulevs.betternether.world.BNWorldGenerator.generate(BNWorldGenerator.java:181)
    at paulevs.betternether.events.EventsHandler.onPopulate(EventsHandler.java:54)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_65_EventsHandler_onPopulate_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:746)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:696)
    at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:746)
    at biomesoplenty.common.world.ChunkGeneratorHellBOP.func_185931_b(ChunkGeneratorHellBOP.java:502)
    at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:301)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:985)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
    at net.minecraft.world.World.func_72964_e(World.java:310)
    at net.minecraft.world.World.func_175726_f(World.java:305)
    at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3283)
    at net.minecraft.world.WorldEntitySpawner.canCreatureTypeSpawnBody(WorldEntitySpawner.java:233)
    at net.minecraft.entity.EntityLiving$SpawnPlacementType.canSpawnAt(EntityLiving.java:1463)
    at net.minecraft.world.WorldEntitySpawner.func_180267_a(WorldEntitySpawner.java:226)
    at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:759)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```
