### ISSUE TITLE
Crashes with fabric-passable-leaves ):

### ISSUE THREAD

**Issue by MrKashew** [paulevsGitch/BetterNether#159]
Crashes with this mod https://www.curseforge.com/minecraft/mc-mods/fabric-passable-leaves

---- Minecraft Crash Report ----
// You're mean.

Time: 7/28/20 5:47 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betternether'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:425)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ExceptionInInitializerError
	at paulevs.betternether.biomes.NetherWartForest.<init>(NetherWartForest.java:37)
	at paulevs.betternether.registry.BiomesRegistry.<clinit>(BiomesRegistry.java:56)
	at paulevs.betternether.BetterNether.onInitialize(BetterNether.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2182/1993821950.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.IllegalStateException: Tag minecraft:leaves used before it was bound
	at net.minecraft.class_5120$class_5121.method_26776(class_5120.java:67)
	at net.minecraft.class_5120$class_5121.method_15141(class_5120.java:78)
	at net.minecraft.class_4970$class_4971.handler$zfk000$getCollisionShape(class_4970.java:1583)
	at net.minecraft.class_4970$class_4971.method_26220(class_4970.java)
	at net.minecraft.class_4970$class_4971.method_26234(class_4970.java:980)
	at net.minecraft.class_3499.method_28054(class_3499.java:134)
	at net.minecraft.class_3499.method_15177(class_3499.java:755)
	at net.minecraft.class_3499.method_15183(class_3499.java:714)
	at paulevs.betternether.structures.StructureNBT.readStructureFromStream(StructureNBT.java:105)
	at paulevs.betternether.structures.StructureNBT.readStructureFromJar(StructureNBT.java:90)
	at paulevs.betternether.structures.StructureNBT.<init>(StructureNBT.java:31)
	at paulevs.betternether.structures.StructureWorld.<init>(StructureWorld.java:17)
	at paulevs.betternether.structures.decorations.StructureWartDeadwood.<clinit>(StructureWartDeadwood.java:15)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7492918288 bytes (7145 MB) / 8522825728 bytes (8128 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.9.1+1.16.1
		antighost: AntiGhost 1.16-fabric0.13.1-1.1.2
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		betternether: Better Nether 3.5.2
		campanion: Campanion 1.1.13+build.35
		cavebiomes: Cave Biomes 0.2.4
		cinderscapes: Cinderscapes 1.0.7+build.43-1.16.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		cotton-client-commands: Cotton Client Commands 1.0.0+1.15.2
		craftpresence: CraftPresence 1.6.6
		dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
		extraalchemy: Extra Alchemy 1.0.4
		fabric: Fabric API 0.16.0+build.384-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		gbfabrictools: GBfabrictools 1.2.2+1.16
		golemsgalore: Golems Galore 0.1.4+mc.1.16.1
		harvest: Harvest 1.2.12
		itemscroller: Item Scroller 0.15.0-dev.20200630.022843
		jankson: Jankson 3.0.0+j1.2.0
		libcd: LibCapableData 2.5.0+1.16.1
		libgui: LibGui 2.1.1+1.16.1
		libstructure: Libstructure 1.3
		lightoverlay: Light Overlay 5.4.1
		magna: Magna 1.1.3-1.16.1
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		mambience: MAmbience 2.1.0-1.16
		minecraft: Minecraft 1.16.1
		minihud: MiniHUD 0.19.0-dev.20200701.005153
		mm: Manningham Mills 2.0
		modmenu: Mod Menu 1.14.5+build.30
		mostructures: Mo' Structures 1.0.0-pre2+mc.1.16
		multiconnect: MultiConnect 1.3.6
		multiconnect-api: MultiConnect API 1.3.6
		namepain: Name Pain 1.2.3
		optifabric: Optifabric 1.1.0-beta2
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		parchment: Parchment 1.0.2+1.15.2
		passable-leaves: Passable Leaves 1.2.0
		phosphor: Phosphor 0.6.0+build.7
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		roughlyenoughitems: Roughly Enough Items 4.10.3
		shapes: Shapes 2.0.0+build.10
		simplevoidworld: Simple Void World 4.0.0
		sneak-through-berries: Sneak Through Berries 1.0.1
		staticdata: Static Data 1.1.2
		stepup: StepUp 1.16-fabric0.13.1-1.0.3
		structurized: Structurized 1.0.0
		tacocraft: TacoCraft 1.3.1+mc.1.16
		terraform: Terraform 2.1.7+build.31
		terrestria: Terrestria 2.0.4+build.50
		torohealth: ToroHealth Damage Indicators 1.16.1-fabric-1
		traverse: Traverse 2.2.14+build.28
		trees-do-not-float: Trees Do Not Float 1.10.90
		tweakeroo: Tweakeroo 0.10.0-dev.20200630.023405
		vanilla-hammers: Vanilla Hammers 2.0.1-1.16.1
		waila: Hwyla 1.9.22
		wildworld: Wild World 1.2.3-1.16
		xaerominimap: Xaero's Minimap 20.18.0
	Launched Version: fabric-loader-0.9.0+build.204-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre10
	OptiFine Build: 20200724-194437
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

**Comment by paulevsGitch** [comment]
"Tag minecraft:leaves used before it was bound" - this is not bug of my mod

**Comment by paulevsGitch** [comment]
Looks like passable leaves use tag before it is created
