### ISSUE TITLE
[1.6.3 + Fabric] IllegalStateException when entering Nether with BN+BYG

### ISSUE THREAD

**Issue by LeLobster** [paulevsGitch/BetterNether#195]
Ran into this in my singleplayer world and after created a fresh profile to test.  
Generating the Nether works fine with only BYG, and works fine with only BetterNether, but adding them both together crashes    
Not sure which mod is the cause exactly so I'm pinging @CorgiTaco too

`better-nether-4.1.3`
`byg-1.0.12`

```
Description: Exception generating new chunk

java.lang.IllegalStateException: Unknown biome id emitted by layers: 186
	at net.minecraft.class_3642.method_16341(class_3642.java:26)
	at voronoiaoc.byg.common.world.dimension.nether.BYGNetherBiomeProvider.method_16359(BYGNetherBiomeProvider.java:34)
	at net.minecraft.class_2794.method_16129(class_2794.java:262)
	at net.minecraft.class_2806.method_16556(class_2806.java:51)
	at net.minecraft.class_2806.method_12154(class_2806.java:219)
	at net.minecraft.class_3898.method_17225(class_3898.java:568)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:562)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:94)
	at net.minecraft.class_3846.method_16900(class_3846.java:137)
	at net.minecraft.class_3846.run(class_3846.java:105)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by CorgiTaco** [comment]
uhhhh. Definitely mine

**Comment by CorgiTaco** [comment]
Uhm let me just..... fix this real fast lol. Thnx for pinging me

**Comment by EnderBro123** [comment]
> Uhm let me just..... fix this real fast lol. Thnx for pinging me

Your the creator of BYG?

**Comment by LeLobster** [comment]
@CorgiTaco Lovely, any idea when It'll be included in a new BYG release?  
I could prob build it from source but have no idea what tools are needed  
I'll just go play some GTA in the meantime lol

**Comment by CorgiTaco** [comment]
@EnderBro123 yup


@LeLobster Try this: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric/files/3075196

LMK If it does or doesnt work

**Comment by EnderBro123** [comment]
@CorgiTaco Oh! Nice to meet you. If you wish to join the Discord then I’ll hand you a link. Will you a special role later though. Not that good with mobile Discord.

**Comment by CorgiTaco** [comment]
@EnderBro123 send it whenever! (Sorry for conversing here btw) :/

**Comment by EnderBro123** [comment]
Here! https://discord.gg/azkRMYB

**Comment by LeLobster** [comment]
@CorgiTaco Just tested in a clean profile first and then my singleplayer world and both where fine now    
Thanks for the quick fix, much appreciated

**Comment by EnderBro123** [comment]
@LeLobster Discord link above if you want to join.
