### ISSUE TITLE
[1.6.3 + Fabric] BN's cleaningPass crashes when it encounters Allure's blocks

### ISSUE THREAD

**Issue by LeLobster** [paulevsGitch/BetterNether#196]
Got a hard crash when generating the Nether for the first time with the BN and [Allure](https://www.curseforge.com/minecraft/mc-mods/allure/) mods installed  

`better-nether-4.1.3`  
`Allure-1.2.7`  

Setting `terrain_cleaning_pass` and `world_fixing_pass` to false "fixes" the crashing, but results in very messy terrain so I'd not really consider it a solution for my singleplayer world   

Assuming it's because both mods contain stalactites etc. (though I'm doubting if Allure's are even supposed to gen in the Nether)    
but I'm not sure which mod is the true cause for the crash  
I'd ping the Allure dev here too but afaik they don't use Github, but It's already reported by someone else to the Allure dev on CF:  
https://www.curseforge.com/minecraft/mc-mods/allure/issues/8

```
net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:92) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_3233 cannot be cast to class net.minecraft.class_1937 (net.minecraft.class_3233 and net.minecraft.class_1937 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @6e9a5ed8)
	at net.Shad0w.Allure.Blocks.Speleothem.SpeleothemBlock.method_9558(SpeleothemBlock.java:49) ~[Allure-1.2.7.jar:?]
	at net.minecraft.class_4970$class_4971.method_26184(class_4970.java:926) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at paulevs.betternether.world.BNWorldGenerator.fixBlocks(BNWorldGenerator.java:496) ~[better-nether-4.1.3.jar:?]
	at paulevs.betternether.world.BNWorldGenerator.cleaningPass(BNWorldGenerator.java:441) ~[better-nether-4.1.3.jar:?]
	at net.minecraft.class_2794.handler$bei000$customPopulate(class_2794.java:1060) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_2806.method_12151(class_2806.java:89) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:219) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:568) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:562) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:94) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:137) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:105) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
[03:57:57] [Worker-Main-2/WARN]: Worker-Main-2 died
java.util.concurrent.CompletionException: net.minecraft.class_148: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:94) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:137) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:105) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.class_3898.method_17225(class_3898.java:579) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:562) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 11 more
Caused by: java.lang.ClassCastException: class net.minecraft.class_3233 cannot be cast to class net.minecraft.class_1937 (net.minecraft.class_3233 and net.minecraft.class_1937 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @6e9a5ed8)
	at net.Shad0w.Allure.Blocks.Speleothem.SpeleothemBlock.method_9558(SpeleothemBlock.java:49) ~[Allure-1.2.7.jar:?]
	at net.minecraft.class_4970$class_4971.method_26184(class_4970.java:926) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at paulevs.betternether.world.BNWorldGenerator.fixBlocks(BNWorldGenerator.java:496) ~[better-nether-4.1.3.jar:?]
	at paulevs.betternether.world.BNWorldGenerator.cleaningPass(BNWorldGenerator.java:441) ~[better-nether-4.1.3.jar:?]
	at net.minecraft.class_2794.handler$bei000$customPopulate(class_2794.java:1060) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_2806.method_12151(class_2806.java:89) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:219) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:568) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:562) ~[intermediary-fabric-loader-0.10.0+build.208-1.16.3.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 11 more
```

**Comment by theishiopian** [comment]
this appears to be a duplicate of #169. Paul has said before the issue is on Allure's end

I highly doubt its due to both having speleothems, that's like saying that if you have copper from two different mods you'll get a crash, which isn't the case.

**Comment by LeLobster** [comment]
@theishiopian apologies, I thought I searched but I might've forgot because of the other issue I opened yesterday at the same time, I'll move to the already open issue after this  

  > I highly doubt

well from reading the crash log it has to do with BN's terrain cleaner not knowing what to do with Allure's blocks (?) I'm a little rusty with Java so I might be totally off but that's how it looks to me   
If you disable the terrain/world cleaning feature of BN then the crash does not happen and the terrain generate
