### ISSUE TITLE
Crash on Init

### ISSUE THREAD

**Issue by TheTirea** [paulevsGitch/BetterNether#209]
Crashing on initialization

I don't know if it's compatibility issue or a problem with the mod.
As far as I know, I don't have any other mod that would mess with the nether.

```
Caused by: java.lang.NoSuchMethodError: net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings.luminance(I)Lnet/fabricmc/fabric/api/object/builder/v1/block/FabricBlockSettings;
        at paulevs.betternether.blocks.BlockCincinnasiteLantern.<init>(BlockCincinnasiteLantern.java:8) ~[better-nether-4.1.7.jar:?]
        at paulevs.betternether.registry.BlocksRegistry.<clinit>(BlocksRegistry.java:71) ~[better-nether-4.1.7.jar:?]
        at paulevs.betternether.BetterNether.onInitialize(BetterNether.java:29) ~[better-nether-4.1.7.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
```

```
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: Could not initialize class paulevs.betternether.registry.BlocksRegistry
Exit Code: -1
```

**Comment by TheTirea** [comment]
Duplicate

found closed issue, that said it's a problem with new fabric version
