### ISSUE TITLE
My game crashes instantly upon launch

### ISSUE THREAD

**Issue by DrDucci** [paulevsGitch/BetterNether#214]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betternether'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.NoSuchMethodError: net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings.luminance(I)Lnet/fabricmc/fabric/api/object/builder/v1/block/FabricBlockSettings;
	at paulevs.betternether.blocks.BlockCincinnasiteLantern.<init>(BlockCincinnasiteLantern.java:8)
	at paulevs.betternether.registry.BlocksRegistry.<clinit>(BlocksRegistry.java:71)
	at paulevs.betternether.BetterNether.onInitialize(BetterNether.java:29)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2302/902550933.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more

Please help!

**Comment by paulevsGitch** [comment]
You use outdated Fabric API, please upgrade to newest one
