### ISSUE TITLE
[Mod conflict] Crashes with Hydrogen by jellysquid3.

### ISSUE THREAD

**Issue by RDKRACZ** [paulevsGitch/BetterNether#264]
I'm getting a crash after Minecraft loads to main menu.
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'betternether'!
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at net.minecraft.client.MinecraftClient.redirect$zbf000$stopFabricInit(MinecraftClient:3360)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:437)
    at net.minecraft.client.main.Main.main(Main:177)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:564)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:564)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class paulevs.betternether.registry.BlocksRegistry
    at paulevs.betternether.registry.BlockEntitiesRegistry.<clinit>(BlockEntitiesRegistry.java:25)
    at paulevs.betternether.registry.BlockEntityRenderRegistry.register(BlockEntityRenderRegistry.java:12)
    at paulevs.betternether.client.BetterNetherClient.onInitializeClient(BetterNetherClient.java:16)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 19 more
```

**Comment by RDKRACZ** [comment]
I saw https://github.com/paulevsGitch/BetterNether/issues/260 but I don't know if it's the same issue, if yes then I'm sorry for a duplicate.

**Comment by paulevsGitch** [comment]
Yes, this is the same bug (I think), and it is not on BN side
