### ISSUE TITLE
Better nether 5.0.5 doesn't start on 1.16.4

### ISSUE THREAD

**Issue by BotiBoster** [paulevsGitch/BetterNether#288]
I try to load the game and it rapidly comes with an error.

I have the log so you can see what happens.

[12:22:41] [main/INFO]: Loading for game Minecraft 1.16.4
[12:22:41] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: betternether requires {minecraft @ [>1.16.4]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:177) ~[fabric-loader-0.11.1.jar:?]
	... 5 more

It says the mod is not there but is the only mod that i'm trying to load. 
please some help

**Comment by paulevsGitch** [comment]
BetterNether 5.0.5 is a mod for 1.16.5
