### ISSUE TITLE
Hydrogen Jellyfish crash

### ISSUE THREAD

**Issue by glossnyx** [paulevsGitch/BetterNether#289]
```
java.lang.Error: Watchdog
	at java.base@15.0.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@15.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at net.minecraft.class_1255.method_20813(class_1255.java:139)
	at net.minecraft.class_1255.method_18857(class_1255.java:129)
	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:1269)
	at net.minecraft.class_3215.method_12121(class_3215.java:1165)
	at net.minecraft.class_2802.method_12126(class_2802.java:16)
	at net.minecraft.class_1937.method_8390(class_1937.java:787)
	at paulevs.betternether.entity.EntityHydrogenJellyfish.canSpawn(EntityHydrogenJellyfish.java:237)
	at net.minecraft.class_1317$$Lambda$2614/0x00000008012e39a0.test(Unknown Source)
	at net.minecraft.class_1317.method_20638(class_1317.java:154)
	at net.minecraft.class_1948.method_24934(class_1948.java:330)
	at net.minecraft.class_1948.method_24930(class_1948.java:259)
	at net.minecraft.class_1948.method_8663(class_1948.java:197)
	at net.minecraft.class_1948.method_27821(class_1948.java:185)
	at net.minecraft.class_3215.method_20801(class_3215.java:388)
	at net.minecraft.class_3215$$Lambda$5010/0x0000000801765d40.accept(Unknown Source)
	at java.base@15.0.1/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraft.class_3215.method_14161(class_3215.java:368)
	at net.minecraft.class_3215.method_12127(class_3215.java:337)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$4700/0x000000080166fbc0.run(Unknown Source)
	at java.base@15.0.1/java.lang.Thread.run(Thread.java:832)
```

Details:

```
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (aarch64) version 5.8.9-2-ARCH
	Java Version: 15.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 3041757696 bytes (2900 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms5G -Xmx5G
	Fabric Mods: 
		adorn: Adorn 1.12.2+1.16.4
		adventurez: AdventureZ 1.1.5
		allstackable: All Stackable 1.2.7
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bag_of_feathers: Bag of Feathers 1.0.0
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterend: Better End 0.8.3-beta
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betternether: Better Nether 5.0.5
		bettersleeping: Better Sleeping 0.4.0
		caelus: Caelus API 0.0.9-1.16.3
		campanion: Campanion 1.3.1+build.51
		cardinal-components-base: Cardinal Components API (base) 2.7.2
		cardinal-components-entity: Cardinal Components API (entities) 2.7.2
		cardinal-components-item: Cardinal Components API (items) 2.7.2
		cardinal-components-world: Cardinal Components API (worlds) 2.6.0
		cinderscapes: Cinderscapes 1.3.0+build.51
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.3
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		couplings: Couplings 1.3.3
		curios: Curios API 0.0.10-1.16.3
		curiouselytra: Curious Elytra 1.1.0-1.16.3
		curiousshulkerboxes: Curious Shulker Boxes 1.1.0-1.16.3
		customportals: Custom Portals 1.3.0
		disco: Disco 1.0.0
		disco-pasudamoyka: Disco Pasudamoyka 1.0.0
		elytraboosters: Elytra Boosters Mod 1.1.0
		fabric: Fabric API 0.28.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.11.1
		fastfurnace: FastFurnace 2.3
		harvest: Harvest 1.2.12
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 15
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.1.0+1.16.3
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.1-SNAPSHOT
		minecraft: Minecraft 1.16.5
		mooblooms: Mooblooms 1.3.2
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		overhauled-end-cities: Overhauled End Cities 1.1
		phosphor: Phosphor 0.6.0+build.7
		player-roles: Player Roles 1.2.0
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.4-1.7.3
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		terrestria: Terrestria 2.1.5+build.28
		trash-disposal: Trash Disposal 1.0.0
		traverse: Traverse 3.0.3+build.13
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		vibes: Vibes 1.0.0
		voyager: Voyager 1.0.0
		yungsapi: YUNG's API 1.16.4-Fabric-1
```

**Comment by Kizuati** [comment]
duplicate of #281

**Comment by paulevsGitch** [comment]
This one looks more like random server error

**Comment by glossnyx** [comment]
I think you're right. I posted this here because this mod was the only one mentioned in the crash log, but I'm starting to think it's a completely different issue.
