### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by theside9** [paulevsGitch/BetterNether#337]
When I run with the creation mode, the following crash log appears
modversion:1.5.1
MCVersion:1.16.5

[23:54:05] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 46119328-ae2b-4ee4-ab98-b19bb18c96d1
[23:54:05] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception while ticking
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap.computeIfAbsent(HashMap.java:1134) ~[?:?] {}
	at net.minecraft.world.gen.feature.template.TemplateManager.func_200219_b(SourceFile:64) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.gen.feature.template.TemplateManager.func_200220_a(SourceFile:54) ~[?:?] {re:mixin,re:classloading}
	at net.aurelj.dungeonsarise.procedures.WindmillFoundationUpdateTickProcedure.executeProcedure(WindmillFoundationUpdateTickProcedure.java:53) ~[dungeons_arise:?] {re:classloading}
	at net.aurelj.dungeonsarise.block.WindmillFoundationBlock$CustomBlock.func_225534_a_(WindmillFoundationBlock.java:77) ~[dungeons_arise:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227033_a_(AbstractBlock.java:620) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.server.ServerWorld.func_205338_b(ServerWorld.java:591) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerTickList.func_205365_a(SourceFile:84) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:336) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:A}
	... 5 more
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by paulevsGitch** [comment]
This is a tracker for BetterNether bugs, your issue is not with BetterNether
