### ISSUE TITLE
Crash with Bukkit/Mohist

### ISSUE THREAD

**Issue by DaringShepard** [paulevsGitch/BetterNether#36]
Hello there,
When using your mod with a Bukkit integration for Forge ([Mohist](https://github.com/Mohist-Community/Mohist/)), a crash happens due to the "Find City" command simply existing.

As the error log suggests, it would appear to be due to the fact that BetterNether's CommandFindCity class can't be cast to Minecraft's CommandBase class.

```
Description: Exception in server tick loop

java.lang.ClassCastException: paulevs.betternether.commands.CommandFindCity cannot be cast to net.minecraft.command.CommandBase
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.setVanillaCommands(CraftServer.java:441)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:413)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:319)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
	at java.lang.Thread.run(Thread.java:748)
```

Full crash report:
https://hastebin.com/raw/eneveniqid

**Comment by paulevsGitch** [comment]
Yes, it is not instance of Command Base. Has forge server same issue?

**Comment by DaringShepard** [comment]
> Has forge server same issue?

It runs just fine when running Forge by itself, no crashes. It only crashes once you introduce Bukkit/Mohist to the server.

But I see you've marked it as fixed it in the latest commits, so hopefully that resolves the issue!

**Comment by paulevsGitch** [comment]
Yes, new version will be released in some hours.
