### ISSUE TITLE
Firefly crash?

### ISSUE THREAD

**Issue by generrosity** [paulevsGitch/BetterNether#4]
Games crashes with one error, but log says another. Crash occurs at login of the ops character in nether. Seems to work fine when files used in singleplayer.

https://pastebin.com/VcjBpwNa

[19:08:44] [Server thread/ERROR] [FML]: Encountered an exception while constructing entity 'betternether:firefly'
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_172]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_172]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_172]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_172]
        at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:305) [EntityEntryBuilder$ConstructorFactory.class:?]
        at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:291) [EntityEntryBuilder$ConstructorFactory.class:?]
        at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:68) [EntityEntry.class:?]
        at net.minecraft.world.biome.Biome$SpawnListEntry.newInstance(Biome.java:655) [anh$c.class:?]
        at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:141) [anb.class:?]
        at net.minecraft.world.WorldServer.tick(WorldServer.java:203) [oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.NoSuchMethodError: paulevs.betternether.entities.EntityFirefly.func_184227_b(D)V
        at paulevs.betternether.entities.EntityFirefly.<init>(EntityFirefly.java:64) ~[EntityFirefly.class:?]
        ... 15 more
[19:08:44] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
        at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:149) ~[anb.class:?]
        at net.minecraft.world.WorldServer.tick(WorldServer.java:203) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) ~[MinecraftServer.class:?]
        ... 4 more

**Comment by paulevsGitch** [comment]
At this time nothing, I think. It seems I know where problem is, I will try fix it to next release.

**Comment by paulevsGitch** [comment]
Looks like I fixed it. In next release (in the near days) it must work fine. After release, I will close this branch, but if this bug will appear again please open a new issue.

**Comment by paulevsGitch** [comment]
Fixed in new release
