### ISSUE TITLE
[Bug] Error while install with NetherEx on Sponge

### ISSUE THREAD

**Issue by SettingDust** [paulevsGitch/BetterNether#41]
https://github.com/LogicTechCorp/NetherEx/issues/214

[]spongeforge-1.12.2-2838-7.1.7.jar
forge-1.12.2-14.23.5.2847-universal.jar

**Log on CLIENT**. NO ERROR ON SERVER. I tried to copy the correct world from local, not good
```
[01:03:21] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task

java.util.concurrent.ExecutionException: java.lang.RuntimeException: VarInt too big

	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_231]

	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_231]

	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]

	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]

	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]

	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

Caused by: java.lang.RuntimeException: VarInt too big

	at net.minecraft.network.PacketBuffer.func_150792_a(PacketBuffer.java:206) ~[gy.class:?]

	at net.minecraft.world.chunk.BlockStatePaletteLinear.func_186038_a(SourceFile:50) ~[axy.class:?]

	at net.minecraft.world.chunk.BlockStateContainer.func_186010_a(BlockStateContainer.java:105) ~[axp.class:?]

	at net.minecraft.world.chunk.Chunk.func_186033_a(Chunk.java:1170) ~[axw.class:?]

	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:745) ~[brz.class:?]

	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[je.class:?]

	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[je.class:?]

	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_231]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_231]

	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]

	... 9 more

[01:03:20] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task

java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 16

	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_231]

	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_231]

	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]

	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]

	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]

	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

Caused by: java.lang.ArrayIndexOutOfBoundsException: 16

	at net.minecraft.world.chunk.BlockStatePaletteLinear.func_186041_a(SourceFile:24) ~[axy.class:?]

	at net.minecraft.world.chunk.BlockStateContainer.func_186014_b(BlockStateContainer.java:81) ~[axp.class:?]

	at net.minecraft.world.chunk.BlockStateContainer.func_186013_a(BlockStateContainer.java:76) ~[axp.class:?]

	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_177484_a(ExtendedBlockStorage.java:87) ~[axx.class:?]

	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:560) ~[axw.class:?]

	at net.minecraft.world.World.func_180501_a(World.java:343) ~[amu.class:?]

	at net.minecraft.client.multiplayer.WorldClient.func_180503_b(WorldClient.java:366) ~[bsb.class:?]

	at net.minecraft.client.network.NetHandlerPlayClient.func_147287_a(NetHandlerPlayClient.java:730) ~[brz.class:?]

	at net.minecraft.network.play.server.SPacketMultiBlockChange.func_148833_a(SourceFile:53) ~[io.class:?]

	at net.minecraft.network.play.server.SPacketMultiBlockChange.func_148833_a(SourceFile:13) ~[io.class:?]

	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_231]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_231]

	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]

	... 9 more

[01:03:20] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task

java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: readerIndex(33761) + length(2048) exceeds writerIndex(34268): UnpooledHeapByteBuf(ridx: 33761, widx: 34268, cap: 34268/34268)

	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_231]

	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_231]

	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]

	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]

	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]

	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

Caused by: java.lang.IndexOutOfBoundsException: readerIndex(33761) + length(2048) exceeds writerIndex(34268): UnpooledHeapByteBuf(ridx: 33761, widx: 34268, cap: 34268/34268)

	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396) ~[AbstractByteBuf.class:4.1.9.Final]

	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1383) ~[AbstractByteBuf.class:4.1.9.Final]

	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:850) ~[AbstractByteBuf.class:4.1.9.Final]

	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:858) ~[AbstractByteBuf.class:4.1.9.Final]

	at net.minecraft.network.PacketBuffer.readBytes(PacketBuffer.java:989) ~[gy.class:?]

	at net.minecraft.world.chunk.Chunk.func_186033_a(Chunk.java:1175) ~[axw.class:?]

	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:745) ~[brz.class:?]

	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96) ~[je.class:?]

	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18) ~[je.class:?]

	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_231]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_231]

	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]

	... 9 more

```

![image](https://user-images.githubusercontent.com/19922286/73595884-5a247a00-4558-11ea-89c6-121b5759a8f4.png)

**Comment by paulevsGitch** [comment]
Did you test mods separately?

**Comment by SettingDust** [comment]
> Did you test mods separately?

Both.

1.
Generator: minecraft:nether
Dimension: minecraft:nether
No NetherEx blocks
![image](https://user-images.githubusercontent.com/19922286/73602110-03935c00-45a9-11ea-856c-8d14cfff84e5.png)

2. 
Generator: minecraft:nether
Dimension: netherex:nether

3.
Generator: default
Dimension: netherex:nether

It's ok. So, It's my fault. I haven't test totally. NetherEX world have to create with default generator.

Only BetterNether

4.
Generator: minecraft:nether
Dimension: minecraft:nether

It's OK.
