### ISSUE TITLE
Disabled mobs will cause spawners in dungeons to crash the game

### ISSUE THREAD

**Issue by llndqvst** [paulevsGitch/BetterNether#417]
Loading certain structures with naga disabled causes the game/server to crash.

This can be reproduced by setting naga to false and entering the nether on seed `-1693642105` and going to `171 42 335`. The game will crash with `java.util.NoSuchElementException` as soon as you trigger the spawner inside.

Log:
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2021-09-22, 16:47
Description: Ticking block entity

java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at net.minecraft.class_1917.handler$bcj000$serverTickMixin(class_1917.java:1030)
	at net.minecraft.class_1917.method_31588(class_1917.java:106)
	at net.minecraft.class_2636.method_31697(class_2636.java:56)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941)
	at net.minecraft.class_1937.method_18471(class_1937.java:474)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.Optional.get(Optional.java:143)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$cdp000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:896)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941)
	at net.minecraft.class_1937.method_18471(class_1937.java:474)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- Block entity being ticked --
Details:
	Name: minecraft:mob_spawner // net.minecraft.class_2636
	Block: Block{minecraft:spawner}
	Block location: World: (181,36,328), Section: (at 5,4,8 in 11,2,20; chunk contains blocks 176,0,320 to 191,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{minecraft:spawner}
	Block location: World: (181,36,328), Section: (at 5,4,8 in 11,2,20; chunk contains blocks 176,0,320 to 191,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)

-- Affected level --
Details:
	All players: 1 total; [class_3222['fruity1'/373, l='ServerLevel[New World]', x=170.20, y=44.75, z=336.06]]
	Chunk stats: 2209
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (240,63,112), Section: (at 0,15,0 in 15,3,7; chunk contains blocks 240,0,112 to 255,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 19808 game time, 19808 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 83569 (now: false), thunder time: 68635 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1523042824 bytes (1452 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 4,00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon RX 5600 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=27.20.1034.6
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 1,60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 19268,27
	Virtual memory used (MB): 12508,87
	Swap memory total (MB): 2944,00
	Swap memory used (MB): 2,00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	Fabric Mods: 
		additionaladditions: Additional Additions 2.1.3
		adorn: Adorn 2.1.5+1.17.1
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.2.11
		amecsapi: Amecs API 1.1.4+mc21w16a
		antiqueatlas: Antique Atlas 6.1.0-fabric-mc1.17.1
		appleskin: AppleSkin mc1.17-2.1.3
		architectury: Architectury 2.5.27
		artifality: Artifality 0.3.5
		battletowers: Battle Towers 3.4.0-1.17.1
		bclib: BCLib 0.3.1
		beaconoverhaul: Beacon Overhaul 1.4.1+1.17
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.1
		betterend: Better End 0.11.0-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		biom4st3r_repackaged_expressions: expj4_repackaged 0.1.0
		blame: Blame 1.17-4.2.0-fabric
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3-1.17.1
		builtinservers: Builtin Servers 1.0.1-BETA+1.17
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		chat_plus: Chat+ 2.1.5
		cleardespawn: Clear Despawn 1.17.1-1.1.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		coat: Coat 1.0.0-beta.11
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		conjuring: Conjuring 1.0.7
		creeperaiupdated: Creeper AI Updated 1.4.0
		creeperspores: Creeper Spores 1.6.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portals 0.0.1-beta33-1.17
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dragonloot: DragonLoot 1.0.9
		drinkbeer: Drink Beer 2.1
		dungeons_arise: When Dungeons Arise 2.1.48-fabric
		eldritch_mobs: Eldritch Mobs 1.9.6
		enchant_giver: Enchant Giver 1.1.0
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		extra_enchants: Extra Enchants 0.1.4
		fabric: Fabric API 0.40.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.3+4658223018
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.4+4658223018
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.2+ffb6d41e18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.1+4658223018
		fabricloader: Fabric Loader 0.11.6
		fiber: fiber 0.23.0-2
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.9
		gateofbabylon: Gate Of Babylon 1.5.1-1.17.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.14
		go-fish: Go Fish 1.3.0-beta-1.17.1
		goosiklib: Goosik Lib 0.1.0
		graveyard: The Graveyard 1.0
		guardiansgalore: GuardiansGalore 1.17.1-2.1
		harvest_scythes: Harvest Scythes 2.0.6
		hookshot: Hookshot 20.0
		hydrogen: Hydrogen 0.3
		incantationem: Incantationem 1.1.2+1.17.1
		indium: Indium 1.0.0+mc1.17.1
		inspecio: Inspecio 1.1.0+1.17
		interactic: Interactic 0.1.5-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 16
		kirin: Kirin UI 1.9.1
		krypton: Krypton 0.1.4
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.7+1.17.1
		libninepatch: LibNinePatch 1.1.0
		litematica: Litematica 0.0.0-dev.20210906.183617
		lithium: Lithium 0.7.4
		maelstrom_library: Maelstrom Library 1.2.2-1.17.1
		malilib: MaLiLib 0.10.0-dev.24
		mcda: MC Dungeons Armors 1.7.10
		mcdw: MC Dungeons Weapons 3.4.2
		midnightlib: MidnightLib 0.2.5
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.12
		moenchant_lib: Mo'Enchantment Library 0.1.4
		moenchantments: Mo'Enchantments 1.18.0
		morevillagers-fabric: MoreVillagersFabric 2.1.0-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mousewheelie: Mouse Wheelie 1.7.3-newconfig.3+mc1.17.1-pre1
		multipart_entities: MultipartEntities 1.1.3-1.17.1
		mystuff: Where Is My Stuff 1.1.0
		namepain: Name Pain 1.4.0
		netherchest: Nether Chest 2.0
		npcvariety: NPC Variety 2.1.2
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		outvoted: Outvoted 2.0.0-alpha.13
		owo: OwO 0.1.1
		particle_emitter_biom4st3r: Particle Emitters LIB 0.1.0
		patchouli: Patchouli 1.17-54-FABRIC
		polymorph: Polymorph 0.0.13-1.17.1
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		ratsmischief: Rat's Mischief 1.2.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		redbits: Red Bits 1.10.0
		reroll: Reroll 1.3.0-1.17.1
		rocks: This Rocks! 1.5.0
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		salutem: Salutem 1.2.1
		seamless_loading_screen: Seamless Loading Screen 1.3.6+1.17.1
		seedy-behavior: Seedy Behavior 1.0.1
		sihywtcamc: sihywtcamc 1.4.1+1.17.1
		sihywtcamd: sihywtcamd 1.5.2+1.17.1
		sodium: Sodium 0.3.2+build.7
		speedyhopper: Speedy Hopper 1.1-1.17-1
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight 1.0.0+fabric.73f6d37
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		stickyhopper: Sticky Hopper 2.3-1.17-1
		stonevaults: Stonevaults 1.1.0
		strawdummy: Straw Dummy 1.5.0
		structure-helpers: Structure Helpers 3.2.0
		syncmatica: Syncmatica 0.2.6
		the_aether: The Aether 1.17.1-1.5.0
		toolstats: Tool Stats 2.0.1
		tooltipfix: ToolTip Fix 1.0.3-1.16
		totemicoverhaul: Totemic Overhaul 1.2
		trinkets: Trinkets 3.0.4
		tweed: Tweed API 3.0.0-beta.22
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.1
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.1
		villagernames: Villager Names 2.0.0
		visuality: Visuality 0.1.3
		voidz: VoidZ 1.0.5
		wandering_collector: Wandering Collector 1.0.2+mc1.17
		waystones: Waystones 2.0.4
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.6
		xp_storage: XP Storage 1.4.2+1.17.1
		yungsapi: YUNG's API 1.17-Fabric-16
	Player Count: 1 / 8; [class_3222['fruity1'/373, l='ServerLevel[New World]', x=170.20, y=44.75, z=336.06]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by paulevsGitch** [comment]
If you disable mob that has spawner - this will result as crash, its better to just remove their spawn from biomes

**Comment by llndqvst** [comment]
Okay, thanks for the tip, didn't even consider that option. How do I remove them from spawning in a biome? Is setting weight to 0 sufficient?

**Comment by Fireface677** [comment]
This should work

**Comment by quiqueck** [comment]
This should be fixed in 6.0.3. I'll have a look if I can backport this to the 1.17 version...

**Comment by Plaga33** [comment]
Even tho 6.0.3. version doesn't have this bug I'm having the same issue while playing with 6.0.2. version of the mod. I would upgrade but considering I'm playing with other mods for mc 1.18 I don't want to migrate to mc 1.18.1 yet. Is there any way I could deal with this on my own? Editing some config files maybe or something else?

**Comment by quiqueck** [comment]
You probably know this, but for the record: https://www.minecraft.net/en-us/article/important-message--security-vulnerability-java-edition  (That is why I don't build against 1.18 anylonger)

Unfortunately, there is no easy way to mitigate this. There are there structure nbt's included in the mod (`betternether/structures/laval/pyramid_3`, `betternether/structures/laval/pyramid_4`, `betternether/structures/ghast_hive`) that will cause the issue when placed in the world. You may be able to override them with the fixed version using a data- or resourcepack. But I do not have any experience with that.

**Comment by Honeth** [comment]
For those that wish to use the 1.18 version for whatever reason.

in the Biomes.json config you can chance the spawn frequency of the specific structures.

Change the pyramid_3 , pyramid_4 and ghast_hive to 0 chance. (credit for the specific structures towards Quiqueck)

Get a world file editor to go and delete the spawners from the structures that spawned into your world already.

Most world file editors will show missing textures due to not having the modded minecraft block textures so heads up on that. I personally used the Editor called "Amulet"

other option would be deleting the entire Nether dimension so it get's generated cleanly after changing the config.

**Comment by paulevsGitch** [comment]
This bug was already fixed, and the latest version is compatible with 1.18

**Comment by llndqvst** [comment]
Since my original issue has been fixed I’m closing this.
