### ISSUE TITLE
Sign text doesn't work

### ISSUE THREAD

**Issue by werewolfboyfriend** [paulevsGitch/BetterNether#420]
On SMP, text on BetterNether signs doesn't appear to anyone but the player posting the sign. Text eventually disappears for them, as well.  Also a console error:

```
03.10 19:49:24 [Server] Server thread/FATAL Error executing task on Server
03.10 19:49:24 [Server] INFO java.lang.NullPointerException: Cannot store to object array because "this.textBeingEdited" is null
03.10 19:49:24 [Server] INFO at paulevs.betternether.blockentities.BNSignBlockEntity.setTextOnRow(BNSignBlockEntity.java:115) ~[better-nether-5.1.3.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.class_3244.handler$bbd000$signUpdate(class_3244.java:4160) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.class_3244.method_12071(class_3244.java) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.class_2877.method_12509(class_2877.java:35) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.class_2877.method_11054(class_2877.java:7) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
03.10 19:49:24 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by quiqueck** [comment]
Fixed in v5.3.5
