### ISSUE TITLE
[Bug] crash when entering the nether.

### ISSUE THREAD

**Issue by MSandro** [paulevsGitch/BetterNether#450]
### What happened?

I am not 100% sure if it is BetterNether or maybe a compatibillity issue, but once I entered the Nethere, the game crashes.
Now I removed BetterNether and it doesn't crash anymore!

### BetterNether

5.3.13

### BCLib

0.5.5

### Fabric API

0.44.0

### Fabric Loader

0.12.8

### Minecraft

1.17.1

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/6/21, 8:49 AM
Description: Exception ticking world

java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at net.minecraft.class_1948.method_24930(class_1948.java:259)
	at net.minecraft.class_1948.method_8663(class_1948.java:199)
	at net.minecraft.class_1948.method_27821(class_1948.java:187)
	at net.minecraft.class_3215.redirect$cke000$injectSpawn(class_3215.java:580)
	at net.minecraft.class_3215.method_20801(class_3215.java:368)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraft.class_3215.method_14161(class_3215.java:355)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.Random.nextInt(Random.java:388)
	at net.minecraft.class_1948.method_24930(class_1948.java:259)
	at net.minecraft.class_1948.method_8663(class_1948.java:199)
	at net.minecraft.class_1948.method_27821(class_1948.java:187)
	at net.minecraft.class_3215.redirect$cke000$injectSpawn(class_3215.java:580)
	at net.minecraft.class_3215.method_20801(class_3215.java:368)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraft.class_3215.method_14161(class_3215.java:355)
	at net.minecraft.class_3215.method_12127(class_3215.java:324)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)

-- Affected level --
Details:
	All players: 1 total; [class_3222['MSandro'/155, l='ServerLevel[nether]', x=1.21, y=71.00, z=2.68]]
	Chunk stats: 1521
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (8,72,8), Section: (at 8,8,8 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 530 game time, 530 day time
	Level name: nether
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 13343 (now: false), thunder time: 135582 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1963121928 bytes (1872 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 2700X Eight-Core Processor         
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.13025.5005
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30666.90
	Virtual memory used (MB): 20911.72
	Swap memory total (MB): 14336.00
	Swap memory used (MB): 146.93
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 2.2.0
		adorn: Adorn 2.3.1+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancements-enlarger: Advancements Enlarger 0.2.4
		advdebug: Advancements Debug 2.3.0
		ae2wtlib: AE2WTLib 9.0.0-beta.8
		agape_space: Space Dimensions 0.4.1
		alloy_forgery: Alloy Forgery 2.0.6
		amecsapi: Amecs API 1.3.3+mc1.17.1
		appleskin: AppleSkin mc1.17.1-2.2.0
		appletreesrev: Apple Trees Rev. 2.6
		appliedenergistics2: Applied Energistics 2 9.0.0-beta.2
		arcanus: Arcanus 1.23
		architectury: Architectury 2.6.35
		artofalchemy: Art of Alchemy 1.3.4
		audiooutput: AudioOutput 0.0.4
		authme: Auth Me 2.0.0
		auto_planter: AutoPlanter 17.1-fabric
		autoclicker-fabric: Auto Clicker 1.17.1-1.2.1-build.13
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automated_crafting: Automated Crafting 1.3.24+MC1.17-1.17.1
		awesomedungeon: Awesome Dungeon 1.1.2
		awokenworld: Awoken World 2.0.0
		balm-fabric: Balm 1.9.0+0
		bannerpp: Banner++ 2.0.4+mc.1.17-rc1
		barrenisles: Barren Isles 1.0.7
		bclib: BCLib 0.5.5
		beaconoverhaul: Beacon Overhaul 1.4.2+1.17
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterend: Better End 0.12.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.3.13
		bettersleeping: Better Sleeping 0.4.0
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.2
		bewitchment: Bewitchment 1.17-15
		bitsandchisels: BitsAndChisels 2.6.0
		blockshifter: Blockshifter 1.4.0+fabric-1.17.1
		blockus: Blockus 2.2.10+1.17.1
		blue_endless_jankson: jankson 1.2.1
		botania: Botania 1.17.1-422-FABRIC
		bountiful: Bountiful 1.0.0
		breakprogress: Break Progress 1.0.1
		buildinggadgets: st'ructure tools 1.0.5
		campanion: Campanion 2.0.1
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carrier: Carrier 1.8.2
		charm: Charm 3.3.2
		chipped: Chipped 1.1.1
		cleanview: CleanView 1.17.1-v1-fabric
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.1.40
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 7.0.10
		coat: Coat 1.0.0-beta.14
		collective-fabric: Collective (Fabric) 3.13
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_flowpowered_flow-math: flow-math 1.0.3
		com_focamacho_sealconfig: sealconfig 1.2.2
		com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.7-1.17.1
		completeconfig: CompleteConfig 1.1.0
		compostable-rottenflesh: Compostable Rotten Flesh 1.0.0
		computercraft: CC:Restitched 1.97.2
		conjuring: Conjuring 1.0.16
		couplings: Couplings 1.6.0+1.17
		crookedcrooks: Crooked Crooks 2.0.1+1.17.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portal Api 0.0.1-beta46-1.17
		customspawns: Custom Spawns 0.5.1+1.17
		danceofgrowth: Twerk / Crop Dusting Mod 1.0
		dark-enchanting: Dark Enchanting 0.6.0-1.17.1
		datapackportals: Datapack Portals 1.1.0-1.17
		diggusmaximus: Diggus Maximus 1.5.1-1.17
		dimdoors: DimensionalDoors 4.0.0+beta.3-27.10.2021
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		dispenser_configurator: Dispenser Configurator 1.1.1+MC1.17-1.17.1
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		drippyloadingscreen: Drippy Loading Screen 1.4.1
		dynamicfps: Dynamic FPS 2.0.6
		enhanced_quarries: Enhanced Quarries 1.2.0_RC7
		enhancedblockentities: Enhanced Block Entities 0.5+1.17
		expandedstorage: Expanded Storage 7.3.1
		extraalchemy: Extra Alchemy 1.6.1
		extragenerators: Extra Generators 1.1-BETA+1.17
		fabric: Fabric API 0.44.0+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+cb9053d118
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+cf39a74318
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+cf39a74318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+cf39a74318
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+cf39a74318
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+cf39a74318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.1+3447790d18
		fabric-copper-golem: Copper Golem 1.0.1+1.17.1
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+cf39a74318
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+cf39a74318
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.1+377137cc18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.12+e99fbe1218
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.4+cf39a74318
		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+cf39a74318
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+6617390918
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.2+cf39a74318
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.6+2a2bb57318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.4+cf39a74318
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.6+0392f3a618
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+cf39a74318
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+cf39a74318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.6+cf39a74318
		fabric-models-v0: Fabric Models (v0) 0.3.1+cf39a74318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+cf39a74318
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+cf39a74318
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+f907116918
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.7+cf39a74318
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+cf39a74318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+cf39a74318
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+cf39a74318
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+cf39a74318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+cf39a74318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+cf39a74318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+cf39a74318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+cf39a74318
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+377137cc18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.10+f09604ce18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+cf39a74318
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+cf39a74318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.15+cf39a74318
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.3+cf39a74318
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+cf39a74318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.2+cf39a74318
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.3+cf39a74318
		fabrication: Fabrication 2.2.1
		fabricloader: Fabric Loader 0.12.8
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		farmersdelight: Farmer's Delight 1.17.1-0.1.3
		fasttransferlib: Fast Transfer Lib 0.5.6
		ferritecore: FerriteCore 3.1.0
		fiber: fiber 0.23.0-2
		full_slabs: FullSlabs 3.2.2
		gateofbabylon: Gate Of Babylon 1.5.1-1.17.1
		gearreborn: Gear Reborn 1.17-0.1.10
		geckolib3: Geckolib 3.0.30
		glassential: Glassential 1.17-1.2.0
		go-fish: Go Fish 1.3.1-1.17.1
		goblintraders: Goblin Traders 1.4.1
		golemsgalore: Golems Galore 1.0.3-1.17.1
		goml: Get Off My Lawn 1.4.0-beta
		grass_pass: Grass Bypass 1.0.0
		grassseeds-fabric: Grass Seeds (Fabric) 1.6
		gud_recipe_confidence: Recipe Confidence 1.0.2
		guild: Guild 0.3.4
		hardcorequesting: Hardcore Questing Mode 1.17.1-5.8.0
		hctm-base: HCTM Base 3.6.2
		hologram-api: Hologram API 0.2.1+1.17.1
		iknowwhatimdoing: I Know What I'm Doing 3.1.0
		impersonate: Impersonate 2.3.5
		improved-stations: Improved Stations 2.0.7
		incubus_core: Incubus Core 1.6.3
		indrev: Industrial Revolution 1.12.0-BETA
		inmis: Inmis 2.3.2-1.17.1
		iron-jetpacks: Iron Jetpacks 0.4.2
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		justenoughkeys: Just Enough Keys 0.4.3
		kambrik: Kambrik 1.1.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.4-BETA+1.17
		kjsextras: KubeJS Extras 1.4.0
		konkrete: Konkrete 1.3.0
		ksyxis: Ksyxis 1.1
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1701.3.10-build.9999
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		libaddict: libaddict 0.3.0
		libblockattributes: LibBlockAttributes 0.9.0
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.2.2+1.17.1
		libmultipart: LibMultiPart 0.6.0
		libnetworkstack: Lib Network Stack 0.5.0
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.3.0+1.17.1
		lifts: Lifts 1.4-BETA+1.17
		lightestlamp: Lightest Lamps 0.9.6
		lightoverlay: Light Overlay 6.0.1
		locki: Locki 0.5.0
		magna: Magna 1.5.5-1.17-pre4
		mambience: MAmbience 3.2.0+1.17.1
		matrix: Matrix 1.0.0
		mcdict: MCDict 2.1.0+1.17.1
		mcskyblock: MC Skyblock Fabric 1.0.3
		mechanicaldispensers: MechanicalDispensers 3.6
		megane: megane 5.6.0
		megane-applied-energistics-2: megane-applied-energistics-2 5.6.0+9.0.0-beta.1
		megane-base: megane-base 5.6.0
		megane-extra-generators: megane-extra-generators 5.6.0+1.1-BETA-1.17
		megane-fabric-transfer: megane-fabric-transfer 5.6.0+1.5.1-6d0fac4218
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.6.0+0.5.7
		megane-industrial-revolution: megane-industrial-revolution 5.6.0+1.11.0-alpha.4
		megane-kibe: megane-kibe 5.6.0+1.9.3-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.6.0+0.9.0
		megane-modern-industrialization: megane-modern-industrialization 5.6.0+0.6.1
		megane-reborn-core: megane-reborn-core 5.6.0+5.0.11-beta
		megane-runtime: megane-runtime 5.6.0
		megane-team-reborn-energy: megane-team-reborn-energy 5.6.0+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 5.6.0+5.0.11-beta
		megane-vanilla: megane-vanilla 5.6.0+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.6.0+1.3.1
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.1
		mo_glass: Mo Glass 1.5-MC1.17.1
		modern_industrialization: Modern Industrialization 0.7.3
		modmenu: Mod Menu 2.0.14
		more_tooltips: MoreTooltips 1.0.2
		moretags: More Tags 1.2.5
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		morevillagesmod: More Villages Mod 1.0.0
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mousewheelie: Mouse Wheelie 1.8.0+mc1.17.1
		mtq-fix: MTQ Fix 0.2.2
		myron: Myron 1.6.1
		nametagtweaks-fabric: Name Tag Tweaks (Fabric) 1.7
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.5
		no-potion-offset: No Potion Offset ${version}
		offhandoverhaul: Offhand Overhaul 1.2.0
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		oldfishfarm: One Block Fish Farm 1.0.0
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_annotations: annotations 19.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		org_objenesis_objenesis: objenesis 3.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		owo: oωo 0.3.2+1.17
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		patchouli: Patchouli 1.17.1-59-FABRIC
		pehkui: Pehkui 2.6.0+1.14.4-1.18
		placeholder-api: Placeholder API 1.1.2+1.17.1
		plantinajar: Plant In A Jar 2.2.2
		platforms: Platforms 1.1.1
		player-vehicle-desync-fix: Player Vehicle Desync Fix 0.2.2
		playerabilitylib: Pal 1.4.0
		pling: Pling 1.5.0
		polymer: Polymer 0.1.8+1.17.1
		pride: Pride Lib 1.1.0+1.17
		pugh_lib: Pugh Lib ${version}
		qcommon-cfg-core: qcommon-cfg-core 3.3.0
		qcommon-croco: Croco 2.1.1
		randombonemealflowers-fabric: Random Bone Meal Flowers (Fabric) 1.7
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.11-beta
		recast-fabric: Recast (Fabric) 1.5
		recipecache: recipecache 0.2.1-1.17.1
		redbits: Red Bits 1.10.1
		replanter: Replanter 1.3
		repurposed_structures: Repurposed Structures 2.5.7+1.17.1
		resourceful_tools: Resourceful Tools 1.1.23
		resourcemelons: Resource Melons 2.1.0
		rhino: Rhino 1701.1.5-build.71
		right-click-clear: Right Click Clear 2.0.3
		ringsofascension: Rings of Ascension 1.0.1
		roughlyenoughitems: Roughly Enough Items 6.2.335
		rswires: RSWires 4.11.2
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		scf: Super Cobblestone Funnels 2.1.0
		schmucks: Schmucks 1.4.0
		searchlight: Searchlight 1.1.3
		seasons: Fabric Seasons 1.3.1-BETA+1.17
		seedy-behavior: Seedy Behavior 1.0.1
		server_translations_api: Server Translations API 1.4.8+1.17
		sgui: sgui 1.0.0-rc5+1.17.1
		shetiphiancore: ShetiPhianCore 1.1.1
		simple_pipes: SimplePipeTest 0.6.2
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.6.2
		simpletech: SimpleTech 0.0.7
		skyutils: Sky utilities Mod 1.0.5_beta4
		skyvillages: Sky Villages 1.0.1.1-fabric
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.2
		slotlink: slotlink 3.1.7
		smoothboot: Smooth Boot 1.16.5-1.6.0
		someforgepatchesported: Some Forge Patches Ported 1.0.1
		somnus: Somnus API 0.0.14-1.17.1
		soundphysics: Sound Physics 2.1.0
		spatialharvesters: Spatial Harvesters 0.11.12c
		spruceui: SpruceUI 3.3.0+1.17
		stacc: Stacc 1.2.3
		starry_sky: Starry Skies 1.3.0-1.17.1
		statement: Statement 4.1.3+1.14.4-1.17.1
		statement_vanilla_compatibility: Statement Vanilla Compatibility Module 1.0.1+1.16.5-1.17
		steedstopper: Steed Stopper 1.0.1
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stockpile: Stockpile 1.1.5+1.17.1
		stoneholm: Stoneholm 1.3
		stonevaults: Stonevaults 1.1.0
		storagecabinet: Storage Cabinet 1.4.1
		structureworld: Structure World 1.1.1-BETA+1.17
		structurized: Structurized 1.3.0
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.0.11-beta
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		the_aether: Paradise Lost - The Aether Reborn 1.17.1-1.6.3.1
		the_bumblezone: The Bumblezone - Fabric 3.4.1+1.17.1
		things: Things 0.2.7
		thonkutil: ThonkUtil 1.3
		timeinabottle: Time in a Bottle 1.6-mc1.17-fabric
		tooltipfix: ToolTip Fix 1.0.4-1.17.1
		totemmod: Wither Totems Mod 0.3.2
		trapexpansion: Trap Expansion 1.3.3
		trinkets: Trinkets 3.0.4
		truerooms: True Secret Rooms 1.1.5
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.1
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.1
		universal-graves: Universal Graves 1.1.4+1.17.1
		victus: Victus 0.1.4+1.17.1
		wands: Building Wands 2.2.8_mc1.17.1
		waystones: Waystones 2.2.2
		winged: Winged Mod 1.17.1-3.0.0
		wireless_redstone: Wireless Redstone 1.0.1
		wirelessnetworks: Wireless Networks 1.3.1
		wmitaf: WMITAF 1.1.4
		workings: Workings 1.0.7
		wthit: wthit 3.11.2
		xaerominimap: Xaero's Minimap 21.22.3
		xaeroworldmap: Xaero's World Map 1.18.6
		xlpackets: XLPackets 2.1-1.17.1
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.17-Fabric-19
		zihlaunchpads: ZIHLaunchpads 1.2.0
		zombievillagersfromspawner-fabric: Zombie Villagers From Spawner (Fabric) 1.6
	Player Count: 1 / 8; [class_3222['MSandro'/155, l='ServerLevel[nether]', x=1.21, y=71.00, z=2.68]]
	Data Packs: vanilla, Fabric Mods, dimdoors/classic, dimdoors/default, dispenser_configurator/default_dispenser_configurators, fabric-copper-golem/copper_golem
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

### Other Mods

```shell
many ... you can see the list in the crash report.
```

**Comment by paulevsGitch** [comment]
Please don't assign tags to your issues manually. This one is not bug in BetterNether, it is a bug from one of your other mods

**Comment by paulevsGitch** [comment]
As there are no any BN traces I will close this
