### ISSUE TITLE
[compatibility] [Bug]

### ISSUE THREAD

**Issue by AlternateLands** [paulevsGitch/BetterNether#465]
### What happened?

BClib version 1.1.1 is incompatible with Mod Menu version 3.0.0 for Minecraft 1.18.1

BetterNether versions 6.0.3 and 6.0.4 have a performance problem, generally within the Upside-down forest biome from what I've seen, slowing the game to a halt and putting much stress on my disc.

### BetterNether

6.0.4

### BCLib

1.1.1

### Fabric API

0.44.0

### Fabric Loader

0.12.12

### Minecraft

1.18.1

### Relevant log output

```shell
[18:03:21] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[18:03:21] [main/WARN]: Warnings were found!
 - Mod 'Custom Entity Models' (cem) 0.7.0 recommends any version of completeconfig, which is missing!
	 - You should install any version of completeconfig for the optimal experience.
[18:03:21] [main/INFO]: Loading 94 mods:
	- advanced_runtime_resource_pack 0.5.1 via extrasounds
	- amplified_nether 1.0.1
	- architectury 3.2.51
	- automatone 0.5.0 via requiem
	- bcdt_expansion 1.18.1-1.1.1
	- bclib 1.1.1
	- betternether 6.0.4
	- cardinal-components-base 4.0.1 via requiem
	- cardinal-components-entity 4.0.1 via requiem
	- cardinal-components-scoreboard 4.0.1 via requiem
	- cardinal-components-world 4.0.1 via requiem
	- cem 0.7.0
	- chickensshed 1.18.1-1.3
	- chime 1.2.0-SNAPSHOT via requiem
	- cleancut 1.18-4.0-fabric
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48
	- effective 1.0
	- extrasounds 2.1.1+1.18
	- fabric 0.44.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cdc8 via fabric
	- fabric-api-lookup-api-v1 1.4.0+16d92c47c8 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a9c8 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d95c8 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d95c8 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cdc8 via fabric
	- fabric-containers-v0 0.1.18+d154e2c6c8 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73dc8 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d95c8 via fabric
	- fabric-dimensions-v1 2.1.7+43d29571c8 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378ac8 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f17c8 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cdc8 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d95c8 via fabric
	- fabric-item-api-v1 1.3.0+691a79b5c8 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d95c8 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f3c8 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cdc8 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca335c8 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d95c8 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d95c8 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cdc8 via fabric
	- fabric-models-v0 0.3.3+3ac43d95c8 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d95c8 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cdc8 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842ec8 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d95c8 via fabric
	- fabric-particles-v1 0.2.9+526dc1acc8 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via requiem
	- fabric-registry-sync-v0 0.8.5+3ac43d95c8 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d95c8 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d95c8 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cdc8 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d7c8 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d95c8 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cdc8 via fabric
	- fabric-rendering-v1 1.10.3+6b21378ac8 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d95c8 via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d95c8 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d95c8 via fabric
	- fabric-structure-api-v1 2.0.8+295197a7c8 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d95c8 via fabric
	- fabric-textures-v0 1.0.9+3ac43d95c8 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f55c8 via fabric
	- fabric-transfer-api-v1 1.5.5+b4f4f6cdc8 via fabric
	- fabricloader 0.12.12
	- farmersdelight 1.18.1-0.2.0
	- fiber 0.23.0-2 via requiem
	- fiber2cloth 3.1.1 via requiem
	- illuminations 1.10.2
	- impersonate 2.4.0 via requiem
	- iris 1.1.3
	- java 17
	- lambdynlights 2.1.0+1.17
	- locki 0.6.0 via requiem
	- minecraft 1.18.1
	- modmenu 3.0.0
	- mousetweaks 2.18
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_joml_joml 1.10.2 via sodium
	- org_slf4j_slf4j-api 1.7.12 via iris
	- playerabilitylib 1.5.0 via requiem
	- pride 1.1.0+1.17 via lambdynlights
	- reach-entity-attributes 2.1.1 via requiem
	- requiem 2.0.0-beta.3
	- requiem-core 2.0.0-beta.3 via requiem
	- requiemapi 2.0.0-beta.3 via requiem
	- roughlyenoughitems 7.0.352
	- satin 1.7.1 via requiem
	- seedfix 1.0.0 via amplified_nether
	- sodium 0.4.0-alpha5+build.9
	- soundcategories 1.1.0+1.18 via extrasounds
	- spruceui 3.3.0+1.17 via lambdynlights
[18:03:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/Scave/Desktop/Stuff/Installers/MultiMC/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[18:03:22] [main/INFO]: Compatibility level set to JAVA_16
[18:03:22] [main/INFO]: Compatibility level set to JAVA_17
[18:03:22] [main/WARN]: [Satin] Sodium is present, custom block renders may not work
[18:03:22] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[18:03:23] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[18:03:23] [main/INFO]: I used the json to destroy the json
[18:03:23] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[18:03:25] [main/WARN]: Failed to add PDH Counter: \Paging File(_Total)\% Usage, Error code: 0xC0000BB8
[18:03:25] [main/WARN]: Failed to add counter for PDH counter: \Paging File(_Total)\% Usage
[18:03:25] [main/WARN]: Disabling further attempts to query Paging File.
[18:03:26] [main/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[18:03:27] [main/WARN]: Injection warning: LVT in net/minecraft/class_2404::method_10316(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;)Z has incompatible changes at opcode 120 in callback betternether.mixins.common.json:LiquidBlockMixin->@Inject::bn_shouldSpreadLiquid(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;ZLcom/google/common/collect/UnmodifiableIterator;Lnet/minecraft/class_2350;Lnet/minecraft/class_2338;Lnet/minecraft/class_2248;)V from mod betternether.
 Expected: [Z, Lcom/google/common/collect/UnmodifiableIterator;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_2338;, Lnet/minecraft/class_2248;]
    Found: [Z, Lcom/google/common/collect/UnmodifiableIterator;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_2338;]
Available: [Z, Lcom/google/common/collect/UnmodifiableIterator;, Lnet/minecraft/class_2350;, Lnet/minecraft/class_2338;]
[18:03:33] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zni000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[18:03:36] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[18:03:36] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[18:03:36] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[18:03:36] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[18:03:36] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[18:03:36] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[18:03:36] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[18:03:36] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[18:03:37] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[18:03:38] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:03:39] [Render thread/INFO]: Setting user: Alternate_Lands
[18:03:39] [Render thread/INFO]: BCDT Expansion loaded!
[18:03:40] [Render thread/INFO]: [STDOUT]: Registering ModBlocks forbcdt_expansion
[18:03:40] [Render thread/INFO]: [betternether] =^..^=    BetterNether for 1.18    =^..^=
[18:03:46] [Render thread/INFO]: Config loaded.
[18:03:46] [Render thread/INFO]: Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[18:03:46] [Render thread/INFO]: Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[18:03:46] [Render thread/INFO]: Registered plugin provider DefaultClientPlugin [roughlyenoughitems] for REIPlugin
[18:03:46] [Render thread/INFO]: Registered plugin provider DefaultClientRuntimePlugin [roughlyenoughitems] for REIPlugin
[18:03:46] [Render thread/INFO]: Registered plugin provider FarmersDelightModREI [farmersdelight] for REIPlugin
[18:03:46] [Render thread/INFO]: Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[18:03:46] [Render thread/INFO]: Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[18:03:46] [Render thread/INFO]: Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[18:03:46] [Render thread/INFO]: Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[18:03:46] [Render thread/INFO]: Loaded seedfix v1.0.0 by Justsnoopy30!
[18:03:47] [Render thread/WARN]: Unable to set up config due to missing dependencies; using defaults!
[18:03:47] [Render thread/INFO]: Loading 61 entities from Custom Entity Models 0.7.0
[18:03:47] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[18:03:48] [Render thread/INFO]: Looking for updates for Illuminations
[18:03:48] [Render thread/INFO]: Adding shutdown hook for uninstaller to update Illuminations
[18:03:48] [Render thread/INFO]: [LambDynLights] Initializing LambDynamicLights...
[18:03:48] [Render thread/INFO]: [LambDynLights] Configuration loaded.
[18:03:49] [Render thread/INFO]: [STDOUT]: [Mouse Tweaks] Main.initialize()
[18:03:49] [Render thread/INFO]: [STDOUT]: [Mouse Tweaks] Initialized.
[18:03:49] [Render thread/INFO]: Registered plugin provider DefaultClientPlugin [roughlyenoughitems] for REIClientPlugin
[18:03:49] [Render thread/INFO]: Registered plugin provider DefaultClientRuntimePlugin [roughlyenoughitems] for REIClientPlugin
[18:03:49] [Render thread/INFO]: Registered plugin provider FarmersDelightModREI [farmersdelight] for REIClientPlugin
[18:03:49] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[18:03:51] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[18:03:51] [Render thread/INFO]: Shaders are disabled
[18:03:53] [Render thread/INFO]: Hardware information:
[18:03:53] [Render thread/INFO]: CPU: 8x AMD Ryzen 5 2400G with Radeon Vega Graphics 
[18:03:53] [Render thread/INFO]: GPU: Radeon(TM) RX 550 (Supports OpenGL 3.2.14739 Core Profile Forward-Compatible Context 20.50.02.10 27.20.15002.10002)
[18:03:53] [Render thread/INFO]: OS: Windows 10
[18:03:54] [Render thread/WARN]: Method overwrite conflict for getNativeMemoryUsage in sodium.mixins.json:features.debug.MixinDebugHud, previously written by net.coderbot.iris.mixin.MixinDebugScreenOverlay. Skipping method.
[18:03:54] [Render thread/INFO]: Narrator library for x64 successfully loaded
[18:03:54] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Runtime Resource Pack, Automatone, BCDT Expansion, BCLib, Better Nether, Custom Entity Models, ChickensShed, Chime, CleanCut, Cloth Config v6, Effective, Extra Sounds, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Farmer's Delight, Fiber To Cloth, Illuminations, Impersonate, Iris, LambDynamicLights, Locki, Mod Menu, Pal, Pride Lib, Reach Entity Attributes, Requiem, Roughly Enough Items, Satin, Sodium, SpruceUI)
[18:03:54] [Render thread/INFO]: ARRP register - before vanilla
[18:03:54] [Render thread/INFO]: ARRP register - after vanilla
[18:03:55] [Render thread/INFO]: Mixin loaded!
[18:04:00] [Worker-Main-12/WARN]: Unable to load model: 'requiem:pure_soul_vessel#inventory' referenced from: requiem:pure_soul_vessel#inventory: java.io.FileNotFoundException: requiem:models/item/pure_soul_vessel.json
[18:04:06] [Render thread/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[18:04:07] [Render thread/INFO]: Failed to find module info for C:\Users\Scave\Desktop\Stuff\Installers\MultiMC\MultiMC\instances\Legendary Enhanced\natives\lwjgl.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[18:04:07] [Render thread/INFO]: Failed to find module info for C:\Users\Scave\Desktop\Stuff\Installers\MultiMC\MultiMC\instances\Legendary Enhanced\natives\glfw.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[18:04:07] [Render thread/INFO]: Failed to find module info for C:\Users\Scave\Desktop\Stuff\Installers\MultiMC\MultiMC\instances\Legendary Enhanced\natives\lwjgl_opengl.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[18:04:07] [Render thread/INFO]: Failed to find module info for C:\Users\Scave\Desktop\Stuff\Installers\MultiMC\MultiMC\instances\Legendary Enhanced\natives\lwjgl_stb.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[18:04:07] [Render thread/INFO]: Failed to find module info for C:\Users\Scave\Desktop\Stuff\Installers\MultiMC\MultiMC\instances\Legendary Enhanced\natives\OpenAL.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[18:04:07] [Render thread/INFO]: Failed to find module info for C:\Users\Scave\Desktop\Stuff\Installers\MultiMC\MultiMC\instances\Legendary Enhanced\natives\SAPIWrapper_x64.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

### Other Mods

```shell
Appleskin-fabric 2.2.0
Amplified Nether 1.0.1
Architectury 3.2.51
Bcdt expansion 1.1.1
Bclib 1.1.1
Better Nether 6.0.4
Cem 0.7.0
Chickens Shed 1.3
Cleancut 4.0
Cloth config API 6.1.48
Effective 1.0
Extra sounds 2.1.1
Fabric api 0.44.0
Farmer's delight fabric 0.2.0
Illuminations 1.10.2
Iris 1.1.3
Lamb dynamic lights 2.1.0
Mouse tweaks fabric 2.18
Requiem 2.0.0
Roughly Enough Items 7.0.352
Sodium fabric 0.4.0-alpha 5 build 9
```

**Comment by paulevsGitch** [comment]
It's better to post it on BCLib tracker, not on BetterNether tracker, and this issue was already [posted](https://github.com/paulevsGitch/BCLib/issues/58) on it
