### ISSUE TITLE
[Bug] Incompatibility with Mining dimensions

### ISSUE THREAD

**Issue by Sven-M-2018** [paulevsGitch/BetterNether#489]
### What happened?

There's an incompatibility with kwpugh's mod "[Mining dimensions](https://www.curseforge.com/minecraft/mc-mods/mining-dimensions-fabric)".

You can find more info [here](https://github.com/kwpugh/mining_Dimensions-1.17/issues/18).

### BetterNether

6.0.8

### BCLib

1.2.1

### Fabric API

0.45.0

### Fabric Loader

0.12.12

### Minecraft

1.18.1

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 1/4/22, 2:35 PM
Description: Biome decoration

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator:310)
	at net.minecraft.world.chunk.ChunkStatus.method_20613(ChunkStatus:146)
	at net.minecraft.world.chunk.ChunkStatus.md5b439b$lambda$injectLightmapSetup$1$4(ChunkStatus:1046)
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:289)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:599)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91)
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146)
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator:310)
	at net.minecraft.world.chunk.ChunkStatus.method_20613(ChunkStatus:146)
	at net.minecraft.world.chunk.ChunkStatus.md5b439b$lambda$injectLightmapSetup$1$4(ChunkStatus:1046)
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:289)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:599)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91)
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146)
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102)

-- Generation --
Details:
	CenterX: 6
	CenterZ: -2
	Seed: 3656475586962628586
Stacktrace:
	at net.minecraft.class_2794.method_12102(class_2794.java:310)
	at net.minecraft.class_2806.method_20613(class_2806.java:146)
	at net.minecraft.class_2806.md5b439b$lambda$injectLightmapSetup$1$4(class_2806.java:1046)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:599)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Chunk to be generated --
Details:
	Location: 6,-2
	Position hash: -8589934586
	Generator: net.minecraft.class_3754@33d0c5d7
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:605)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:599)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 961
	Level dimension: mining_dims:nethering_dim
	Derived: true
	Level spawn location: World: (704,384,-224), Section: (at 0,0,0 in 44,24,-14; chunk contains blocks 704,0,-224 to 719,255,-209), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Level time: 20002952 game time, 21443864 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 83065 (now: false), thunder time: 38544 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.4.0-91-generic
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2659685392 bytes (2536 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: G200eR2
	Graphics card #0 vendor: Matrox Electronics Systems Ltd. (0x102b)
	Graphics card #0 VRAM (MB): 16.00
	Graphics card #0 deviceId: 0x0534
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 94701.92
	Virtual memory used (MB): 81043.98
	Swap memory total (MB): 62560.00
	Swap memory used (MB): 17063.79
	JVM Flags: 20 total; -Xms6144M -Xmx6144M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalbars: Additional Bars 2.2.1
		adorn: Adorn 3.1.0+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.10
		advancednetherite: Advanced Netherite 1.3.1-1.18.1
		amplified_nether: Amplified Nether for Fabric 1.0.1
		anvilrestoration-fabric: Anvil Restoration (Fabric) 1.1
		aqupdcaracal: Caracal mob 1.18-1.3.5.1
		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.2
		architectury: Architectury 3.4.9
		attributefix: AttributeFix 13.0.3
		awesomedungeon: Awesome Dungeon 2.0.2
		awesomedungeon_ocean: Awesome Dungeon Edition Ocean 1.0.3
		backslot: BackSlot 1.2.4
		backslotaddon: BackSlot Addon 1.0.7
		balm-fabric: Balm 2.4.0+0
		basicshields: Basic Shields [Fabric] 1.2.0-1.18.1
		bcc: BetterCompatibilityChecker fabric-1.0.4
		bclib: BCLib 1.2.1
		beenfo: Beenfo 1.18.1-fabric0.45.0-1.3.3
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.2
		betterbeds: Better Beds 1.2.0
		betterend: Better End 1.0.0
		betternether: Better Nether 6.0.8
		blockshifter: Blockshifter 1.4.1+fabric-1.18
		blockus: Blockus 2.3.4+1.18.1
		blue_endless_jankson: jankson 1.2.1
		bno: Basic Nether Ores 1.18-7.0.0-Fabric
		boatcontainer: BoatContainer 1.0.4
		bountiful: Bountiful 2.0.1
		cardinal-components-base: Cardinal Components API (base) 4.0.1
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.1
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		carrier: Carrier 1.9.0
		castle_dungeons: Castle Dungeons 3.1-1.18-fabric
		chalk: Chalk 1.2.1
		chas: Craftable Horse Armour & Saddle 1.18-1.8-Fabric
		chisel: Chisel Refabricated 1.4.4
		chunky: Chunky 1.2.164
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-common-events-v1: Cloth Common Events v1 1.5.47
		cloth-config: Cloth Config v6 6.1.48
		clumps: Clumps 8.0.4
		collective-fabric: Collective (Fabric) 3.14
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		companion: Companion 1.1.0
		completeconfig: CompleteConfig 1.3.3
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		consistency_plus: Consistency Plus 0.4.3+1.18
		convenient-mobgriefing: Convenient mobGriefing 2.0.2
		cosmetic-armor: Cosmetic Armor 1.2.0
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		craftabletotemofundying: Craftable Totem Of Undying 1.18.1-1.5.0-[FABRIC]
		croptopia: Croptopia 1.8.0
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cryingportals-fabric: Crying Portals (Fabric) 1.2
		customportalapi: Custom Portal Api 0.0.1-beta47-1.18
		cyclepaintings-fabric: Cycle Paintings (Fabric) 2.1
		dawn: Dawn API 3.2.0
		deepslatecutting: Deepslate Cutting 1.3.0
		despawningeggshatch-fabric: Despawning Eggs Hatch (Fabric) 2.3
		dimores: DimensionalOres 1.0.2
		doubledoors-fabric: Double Doors (Fabric) 3.1
		dungeons_arise: When Dungeons Arise 2.1.49c-fabric
		dynview: Dynamic View Mod 1.18-1.5
		easymagic: Easy Magic 3.2.1
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		emerald_tools: Emerald Tools 1.3.33
		enchantinginfuser: Enchanting Infuser 3.1.0
		endgoblintraders: End Goblin Traders 1.4.2
		enhancedcelestials: Enhanced Celestials 2.0.6
		exlineawnings: Exline's Awnings 1.18
		exlinefurniture: Exline's Furniture 1.18.1
		experiencebottler: Experience Bottler 1.18.1+build.1
		experiencebugfix: Experience Bug Fix 18
		fabric: Fabric API 0.45.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d2957165
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cd65
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.6+533be9ba65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f5565
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		fabricshieldlib: Fabric Shield Lib 1.4.5-1.18
		farmingforblockheads: Farming for Blockheads 9.0.2
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		fixedanvilrepaircost-fabric: Fixed Anvil Repair Cost (Fabric) 1.6
		flesh2leather: Flesh2Leather 1.0.2
		flytre-lib-base: Flytre Lib - Base Module 1.3.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.2
		flytre_lib: Flytre Lib 1.4.4
		forgeconfigapiport: Forge Config API Port 3.1.0
		fortune-gives-experience: Fortune Gives Experience 1.1.0
		geckolib3: Geckolib 3.0.23
		geodes: More Geodes 1.2.0
		glassential: Glassential 1.3.0
		go-fish: Go Fish 1.4.1-1.18.1
		gobber2: Gobber2 2.5.57
		goblintraders: Goblin Traders 1.4.1
		grassseeds-fabric: Grass Seeds (Fabric) 1.6
		graveyard: The Graveyard 1.1
		grindenchantments: Grind Enchantments 1.5.0+1.18
		grindstone-is-made-of-stone: Grindstone Is Made Of Stone 2.0
		healingcampfire-fabric: Healing Campfire (Fabric) 3.3
		hplus: Better Hoppers (Hopper+) 3.0.1
		hwg: Happiness is a Warm Gun 1.0.0
		iceberg: Iceberg 1.0.27
		imm_ptl_core: Immersive Portals Core 1.1.8
		immersive_portals: Immersive Portals 1.1.8
		infinitetrading-fabric: Infinite Trading (Fabric) 2.1
		inmis: Inmis 2.4.0-1.18
		inventorysorter: Inventory Sorter 1.8.3-1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		ironfurnaces: Iron Furnaces 3.0.0
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		justsomemusicdiscs: justsomemusicdiscs 1.3.0
		kambrik: Kambrik 3.0.0
		kibe: Kibe 1.9.4-BETA+1.18
		kleeslabs: KleeSlabs 11.0.0
		kubejs: KubeJS 1801.4.0-build.263
		kyrptconfig: Kyrpt Config 1.3.3-1.18
		lazydfu: LazyDFU 0.1.2
		libblockattributes: LibBlockAttributes 0.10.0
		libblockattributes_core: LibBlockAttributes (Core) 0.10.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
		libblockattributes_items: LibBlockAttributes (Items) 0.10.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libraryferret: Library Ferret 1.0.2
		lifts: Lifts 1.4-BETA+1.18
		lithium: Lithium 0.7.7
		lootcrates: Modular Loot Crates 2.6.0-1.18.1
		lovely_snails: Lovely Snails 1.0.3+1.18
		lumiwool: Luminous Wool 1.2.2
		magna: Magna 1.7.0-1.18-pre1
		mavm: More Axolotl Variants Mod 1.0.7a
		maybe-data: Maybe data 1.0.1-1.17
		maybe-more-data: Maybe More Data 1.0.0-1.18
		me_hypherionmc_sdlink-lib: sdlink-lib 1.5.1
		me_hypherionmc_simple-rpc-common: simple-rpc-common 1.0.15
		mesh: Mesh 0.19.0-alpha
		mesh_api: Mesh API 0.19.0-alpha
		minecraft: Minecraft 1.18.1
		minegate-moreblocks: MineGate · MoreBlocks 1.1.8
		mineralchance-fabric: Mineral Chance (Fabric) 1.6
		mining_dims: Mining Dimensions 1.2.38
		mo_glass: Mo Glass 1.6.1-MC1.18.1
		mocolors: Mo' Colors 1.3.0
		modern_industrialization: Modern Industrialization 1.0.2
		more-axolotls: More Axolotls 1.0.2
		more_gems: More Gems 1.3.55
		morebannerfeatures: More Banner Features 1.1.3
		mores: Mores 1.2.7
		morevillagers-fabric: MoreVillagersFabric 3.1.0-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mythic-mounts: Mythic Mounts 1.18-4.0
		nbtcrafting: NBT Crafting 2.1.0+mc1.18-pre1
		netherited: Netherited 1.2.0
		netherportalfix: NetherPortalFix 9.0.0
		nha: Netherite Horse Armor 1.4.0
		no_null_processors: No Null Processors - Fabric 2.0.0+1.18
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18.1
		omega-config: OmegaConfig 1.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		overpoweredmending: OverpoweredMending 2.3.1
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		paintings: Paintings++ 1.0.0.6
		patchouli: Patchouli 1.18.1-63-FABRIC
		petnames-fabric: Pet Names (Fabric) 1.6
		phosphor: Phosphor 0.8.1
		playerabilitylib: Pal 1.4.0
		polymorph: Polymorph 0.0.18-1.18.1
		prefab: Prefab 3.0.0
		pugh_lib: Pugh Lib 1.2.13
		pugh_tools: Pugh Tools 1.1.16
		puzzleslib: Puzzles Lib 3.1.3
		q_misc_util: QMiscUtil 1.1.8
		recipeconditions: Fabric Recipe Conditions 0.4.1
		reinfbarrel: Reinforced Barrels 1.0.5+1.18
		reinfchest: Reinforced Chests 1.0.5+1.18
		reinfcore: Reinforced Core 1.1.2+1.18
		reinfshulker: Reinforced Shulker Boxes 1.1.7+1.18
		repurposed_structures: Repurposed Structures 3.2.0+1.18.1
		resourceful_tools: Resourceful Tools 1.2.29
		rhino: Rhino 1800.1.7-build.92
		roughlyenoughitems: Roughly Enough Items 7.1.357
		rpgstats: RPGStats 4.3.2+1.18.1
		sdlink: Simple Discord Link 1.18.x-1.1
		seedfix: Seed Fix 1.0.0
		server_translations_api: Server Translations API 1.4.8+1.18-pre1
		servercore-fabric: ServerCore-Fabric 1.2.6-1.18.1
		silktouch_spawners: SilkTouch Spawners 0.0.1
		simple-rpc: Simple Rpc 2.7
		simple_shelves: Simple Shelves 1.0.4
		skinnedlanterns: Skinned Lanterns 1.2.0+build.12
		slotlink: slotlink 4.0.4
		spark: spark 1.7.2
		spawnermod: Enhanced Mob Spawners 1.1.2
		starterkit-fabric: Starter Kit (Fabric) 3.1
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stonecutter_recipe_tags: Stonecutter Recipe Tags 2.0.0
		stoneholm: Stoneholm 1.4.1
		storagecabinet: Storage Cabinet 1.4.2
		taxfreelevels: Tax Free Levels 1.3
		team_reborn_energy: Energy 2.0.0-beta1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0.8
		the_loved_ones: The Loved Ones 1.2.0+1.18
		thonkutil: ThonkUtil 2.6.0+1.18
		thonkutil-base: ThonkUtil Base 1.4.0+6a7a08aec8
		thonkutil-capes-v1: ThonkUtil Capes (v1) 1.2.0+a46c8f89c8
		thonkutil-customization: ThonkUtil Customization (v1) 1.0.1+6a7a08aec8
		thonkutil-legacy: ThonkUtil Legacy 1.0.7+6fa117f8c8
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.2.5+6a7a08aec8
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.5+6a7a08aec8
		totw_additions: Towers of the Wild: Additions 1.1.0
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.1.0
		tradingpost: Trading Post 3.1.2
		trampledisablerfabric: Trample Disabler 1.0.4
		trashslot: TrashSlot 11.0.0
		treeharvester-fabric: Tree Harvester (Fabric) 4.1
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.1.0
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.1-1.18.1
		universal_ores: Universal Ores 1.2.1
		untitledduckmod: Untitled Duck Mod 0.3.0
		vanillatweaks: VanillaTweaks 1.0.19
		villagebellrecipe-fabric: Village Bell Recipe (Fabric) 1.3
		villagerdeathmessages-fabric: Villager Death Messages (Fabric) 2.2
		villagernames-fabric: Villager Names (Fabric) 3.5
		villagespawnpoint-fabric: Village Spawn Point (Fabric) 1.8
		voidtotem: VoidTotem (Fabric) 1.18.1-1.1.0
		waystones: Waystones 2.4.1
		wolveswitharmor: Wolves With Armor 1.7.0-1.18
		xaerominimap: Xaero's Minimap 21.23.0
		xaeroworldmap: Xaero's World Map 1.19.0
		xlpackets: XLPackets 2.1-1.17.1
		yigd: You're in Grave Danger 1.2.10
	Server Running: true
	Player Count: 1 / 20; [class_3222['11meter'/12, l='ServerWorld minecraft:overworld world', x=67.41, y=74.00, z=-59.49]]
	Data Packs: vanilla, Fabric Mods, file/customportalsupport.zip (incompatible)
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	Suspected Mods: None
```

**Comment by quiqueck** [comment]
Thanks for reporting this issue. It should be fixed with the next update to BCLib.

**Comment by quiqueck** [comment]
New version is released so I'll close this issue for now. If the bug is not resolved for you, then please reopen it.
