### ISSUE TITLE
[Bug] Disable any blocks in blocks.json the game crash

### ISSUE THREAD

**Issue by BaeyDesola** [paulevsGitch/BetterNether#542]
### What happened?

in the outset i wanted to disable chair, taburet and bar stool, the game crashed.
i find disable any blocks in blocks.json the game crashed.

### BetterNether

6.1.1

### BCLib

1.4.5

### Fabric API

0.51.1

### Fabric Loader

0.14.3

### Minecraft

1.18.1

### Relevant log output

```shell
[01:35:11] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.3
[01:35:11] [main/INFO]: Loading 48 mods:
	- bclib 1.4.5
	- betternether 6.1.1
	- fabric 0.51.1+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.14.3
	- java 17
	- minecraft 1.18.2
[01:35:11] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/1.18.2%20%e8%ae%a1%e5%88%92/BUG/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.3+mixin.0.8.5/sponge-mixin-0.11.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[01:35:11] [main/INFO]: Compatibility level set to JAVA_17
[01:35:13] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[01:35:14] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[01:35:24] [main/INFO]: [bclib] Added Config betternether.main to auto sync (file hash)
[01:35:24] [main/INFO]: [bclib] Added Config betternether.generator to auto sync (file hash)
[01:35:24] [main/INFO]: [bclib] Added Config betternether.blocks to auto sync (file hash)
[01:35:24] [main/INFO]: [bclib] Added Config betternether.items to auto sync (file hash)
[01:35:24] [main/INFO]: [bclib] Added Config betternether.biomes to auto sync (file hash)
[01:35:24] [main/INFO]: [bclib] Added Config betternether.mobs to auto sync (file hash)
[01:35:24] [main/INFO]: [bclib] Added Config betternether.recipes to auto sync (file hash)
[01:35:24] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[01:35:24] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[01:35:26] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[01:35:27] [Render thread/INFO]: Setting user: BaeyDesola
[01:35:27] [Render thread/INFO]: [betternether] =^..^=    BetterNether for 1.18.2    =^..^=
[01:35:32] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[01:35:32] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[01:35:36] [Render thread/INFO]: Narrator library for x64 successfully loaded
[01:35:36] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (BCLib, Better Nether, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader)
[01:35:37] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=Block{minecraft:air}}, Reference{null=Block{minecraft:air}}, Reference{null=Block{minecraft:air}}]
	at net.minecraft.class_2370.method_40276(class_2370.java:330) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_40292(class_2378.java:369) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.handler$zjb001$onStart(class_310.java:5985) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:716) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.3.jar:?]
[01:35:37] [Render thread/INFO]: Stopping!
[01:35:38] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1048) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1026) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:252) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.3.jar:?]
```

**Comment by Little8man** [comment]
Having this exact same issue, does anybody know an alternative to using the blocks.json? I find many of the biomes overly cluttered, and I find the overly detailed 3D models annoying.

**Comment by quiqueck** [comment]
Unfortunatley, there isn't. But we will provide a fix for this.

**Comment by ZenoCoding** [comment]
having a similar issue with items

**Comment by paulevsGitch** [comment]
Please open this issue on the new BN git tracker if it still exists
