### ISSUE TITLE
mod conflict with Immersive Weathering v2.5.2 [Bug] 

### ISSUE THREAD

**Issue by JonCaver** [paulevsGitch/BetterNether#558]
### What happened?

With the update of Immersive weathering there is a crash when entering the nether. I have tried to fix this crash with AstralOrdana from immersive weathering.. [https://github.com/AstralOrdana/Immersive-Weathering/issues/69](url)
They have said there is nothing further they can do with it and asked to post an issue here.

The crash was originally with the (betternether:black_vine) and now it is with the (betternether:Nether_reed_stem) 
latest crash..

---- Minecraft Crash Report ----
// You're mean.

Time: 5/27/22, 8:21 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property class_2746{name=persistent, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{betternether:nether_reed_stem}
at net.minecraft.class_2688.method_11654(class_2688.java:98)
at com.ordana.immersive_weathering.block_growth.hardcoded.LeavesGrowth.tryGrowing(LeavesGrowth.java:34)
at com.ordana.immersive_weathering.block_growth.BlockGrowthHandler.tickBlock(BlockGrowthHandler.java:57)
at net.minecraft.class_3218.handler$cfn000$tickBlocks(class_3218.java:7151)
at net.minecraft.class_3218.method_18203(class_3218.java:489)
at net.minecraft.class_3215.method_14161(class_3215.java:378)
at net.minecraft.class_3215.method_12127(class_3215.java:322)
at net.minecraft.class_3218.method_18765(class_3218.java:311)
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
at net.minecraft.class_1132.method_3748(class_1132.java:97)
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
at java.base/java.lang.Thread.run(Thread.java:833)

### BetterNether

6.1.1

### BCLib

1.4.6

### Fabric API

0.53.4

### Fabric Loader

0.14.5

### Minecraft

1.18.1

**Comment by JonCaver** [comment]
was fixed by other mod

**Comment by conorzurawski** [comment]
Hey I've got the same problem and was wondering if you got a solution worked?
